dataset: brats2021
source_domain: t1
target_domain: t2 
fid_dir: ./fid_stats
valid_path: /disk1/medical/brats2021/validation
batch_size: 8 
size: 256
gpu_id: 0
gpu_ids:
- '01234567'
es_higher_limit: 80 
es_lower_limit: 50
seed: 3